In [70]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix,accuracy_score,r2_score

In [4]:
train_date=pd.read_csv('Data\Train.csv')
test_date=pd.read_csv('Data\Test.csv')

In [13]:
train_date

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [7]:
train_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [5]:
test_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5681 entries, 0 to 5680
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            5681 non-null   object
 1   Item_Weight                4705 non-null   float64
 2   Item_Fat_Content           5681 non-null   object
 3   Item_Visibility            5681 non-null   float64
 4   Item_Type                  5681 non-null   object
 5   Item_MRP                   5681 non-null   float64
 6   Outlet_Identifier          5681 non-null   object
 7   Outlet_Establishment_Year  5681 non-null   int64
 8   Outlet_Size                4075 non-null   object
 9   Outlet_Location_Type       5681 non-null   object
 10  Outlet_Type                5681 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 488.3+ KB

In [9]:
train_date.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [10]:
test_date.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [29]:
train_date['Outlet_Size'].unique()

array(['Medium', 'High', 'Small'], dtype=object)

In [30]:
train_date['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular', 'low fat', 'reg', 'LF'], dtype=object)

In [31]:
train_date['Item_Type'].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Household', 'Baking Goods',
       'Snack Foods', 'Fruits and Vegetables', 'Breakfast',
       'Health and Hygiene', 'Hard Drinks', 'Frozen Foods', 'Canned',
       'Starchy Foods', 'Breads', 'Others', 'Seafood'], dtype=object)

In [32]:
train_date['Outlet_Location_Type'].unique()

array(['Tier 1', 'Tier 3', 'Tier 2'], dtype=object)

In [33]:
train_date['Outlet_Type'].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Supermarket Type3',
       'Grocery Store'], dtype=object)

In [17]:
train_date['Item_Weight'].fillna(train_date['Item_Weight'].mean(),inplace=True)

C:\Users\gaura\AppData\Local\Temp\ipykernel_324\1305472262.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_date['Item_Weight'].fillna(train_date['Item_Weight'].mean(),inplace=True)

In [21]:
train_date.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [22]:
train_date.dropna(inplace=True)

In [23]:
train_date.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [24]:
train_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6113 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            6113 non-null   object
 1   Item_Weight                6113 non-null   float64
 2   Item_Fat_Content           6113 non-null   object
 3   Item_Visibility            6113 non-null   float64
 4   Item_Type                  6113 non-null   object
 5   Item_MRP                   6113 non-null   float64
 6   Outlet_Identifier          6113 non-null   object
 7   Outlet_Establishment_Year  6113 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       6113 non-null   object
 10  Outlet_Type                6113 non-null   object
 11  Item_Outlet_Sales          6113 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 620.9+ KB

In [26]:
train_date.drop('Item_Identifier',axis=1,inplace=True)

In [27]:
train_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6113 entries, 0 to 8522
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                6113 non-null   float64
 1   Item_Fat_Content           6113 non-null   object
 2   Item_Visibility            6113 non-null   float64
 3   Item_Type                  6113 non-null   object
 4   Item_MRP                   6113 non-null   float64
 5   Outlet_Identifier          6113 non-null   object
 6   Outlet_Establishment_Year  6113 non-null   int64
 7   Outlet_Size                6113 non-null   object
 8   Outlet_Location_Type       6113 non-null   object
 9   Outlet_Type                6113 non-null   object
 10  Item_Outlet_Sales          6113 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 573.1+ KB

In [34]:
train_date['Item_Fat_Content'].replace('reg', 'Regular',inplace=True)

In [37]:
train_date['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [36]:
train_date['Item_Fat_Content'].replace('LF', 'Low Fat',inplace=True)
train_date['Item_Fat_Content'].replace('low fat', 'Low Fat',inplace=True)

In [38]:
col=['Item_Fat_Content','Item_Type','Outlet_Size','Outlet_Location_Type','Outlet_Type']
dummies=[]
for column in col:
    dummies.append(pd.get_dummies(train_date[column]))
td=pd.concat(dummies,axis=1)
train_date=pd.concat((train_date,td),axis=1)
train_date=train_date.drop(col,axis=1)

In [40]:
train_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6113 entries, 0 to 8522
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                6113 non-null   float64
 1   Item_Visibility            6113 non-null   float64
 2   Item_MRP                   6113 non-null   float64
 3   Outlet_Identifier          6113 non-null   object
 4   Outlet_Establishment_Year  6113 non-null   int64
 5   Item_Outlet_Sales          6113 non-null   float64
 6   Low Fat                    6113 non-null   bool
 7   Regular                    6113 non-null   bool
 8   Baking Goods               6113 non-null   bool
 9   Breads                     6113 non-null   bool
 10  Breakfast                  6113 non-null   bool
 11  Canned                     6113 non-null   bool
 12  Dairy                      6113 non-null   bool
 13  Frozen Foods               6113 non-null   bool
 14  Fruits and Vegetables      6113 non-null   bool
 15  Hard Drinks                6113 non-null   bool
 16  Health and Hygiene         6113 non-null   bool
 17  Household                  6113 non-null   bool
 18  Meat                       6113 non-null   bool
 19  Others                     6113 non-null   bool
 20  Seafood                    6113 non-null   bool
 21  Snack Foods                6113 non-null   bool
 22  Soft Drinks                6113 non-null   bool
 23  Starchy Foods              6113 non-null   bool
 24  High                       6113 non-null   bool
 25  Medium                     6113 non-null   bool
 26  Small                      6113 non-null   bool
 27  Tier 1                     6113 non-null   bool
 28  Tier 2                     6113 non-null   bool
 29  Tier 3                     6113 non-null   bool
 30  Grocery Store              6113 non-null   bool
 31  Supermarket Type1          6113 non-null   bool
 32  Supermarket Type2          6113 non-null   bool
 33  Supermarket Type3          6113 non-null   bool
dtypes: bool(28), float64(4), int64(1), object(1)
memory usage: 501.5+ KB

In [44]:
z=train_date.iloc[:,3]
z

0       OUT049
1       OUT018
2       OUT049
4       OUT013
5       OUT018
         ...
8517    OUT046
8518    OUT013
8520    OUT035
8521    OUT018
8522    OUT046
Name: Outlet_Identifier, Length: 6113, dtype: object

In [45]:
label=LabelEncoder()

In [46]:
zencode=label.fit_transform(z)
zencode=pd.Series(zencode)
train_date=pd.concat((train_date,zencode),axis=1)

In [47]:
train_date

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Item_Outlet_Sales,Low Fat,Regular,Baking Goods,Breads,...,Medium,Small,Tier 1,Tier 2,Tier 3,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,0
0,9.300,0.016047,249.8092,OUT049,1999.0,3735.1380,True,False,False,False,...,True,False,True,False,False,False,True,False,False,6.0
1,5.920,0.019278,48.2692,OUT018,2009.0,443.4228,False,True,False,False,...,True,False,False,False,True,False,False,True,False,1.0
2,17.500,0.016760,141.6180,OUT049,1999.0,2097.2700,True,False,False,False,...,True,False,True,False,False,False,True,False,False,6.0
4,8.930,0.000000,53.8614,OUT013,1987.0,994.7052,True,False,False,False,...,False,False,False,False,True,False,True,False,False,1.0
5,10.395,0.000000,51.4008,OUT018,2009.0,556.6088,False,True,True,False,...,True,False,False,False,True,False,False,True,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
6108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
6110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
6111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
6112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [49]:
train_date.drop('Outlet_Identifier',axis=1,inplace=True)
train_date.rename(columns={0:"Outlet_Identifier"},inplace=True)
train_date

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Low Fat,Regular,Baking Goods,Breads,Breakfast,...,Medium,Small,Tier 1,Tier 2,Tier 3,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,Outlet_Identifier
0,9.300,0.016047,249.8092,1999.0,3735.1380,True,False,False,False,False,...,True,False,True,False,False,False,True,False,False,6.0
1,5.920,0.019278,48.2692,2009.0,443.4228,False,True,False,False,False,...,True,False,False,False,True,False,False,True,False,1.0
2,17.500,0.016760,141.6180,1999.0,2097.2700,True,False,False,False,False,...,True,False,True,False,False,False,True,False,False,6.0
4,8.930,0.000000,53.8614,1987.0,994.7052,True,False,False,False,False,...,False,False,False,False,True,False,True,False,False,1.0
5,10.395,0.000000,51.4008,2009.0,556.6088,False,True,True,False,False,...,True,False,False,False,True,False,False,True,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
6108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
6110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
6111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
6112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [50]:
a=train_date.iloc[:,3]
a

0       1999.0
1       2009.0
2       1999.0
4       1987.0
5       2009.0
         ...
6101       NaN
6108       NaN
6110       NaN
6111       NaN
6112       NaN
Name: Outlet_Establishment_Year, Length: 7854, dtype: float64

In [51]:
aencode=label.fit_transform(a)
aencode=pd.Series(aencode)
train_date=pd.concat((train_date,aencode),axis=1)

In [52]:
train_date.drop('Outlet_Establishment_Year',axis=1,inplace=True)
train_date.rename(columns={0:"Outlet_Establishment_Year"},inplace=True)
train_date

,Item_Weight,Item_Visibility,Item_MRP,Item_Outlet_Sales,Low Fat,Regular,Baking Goods,Breads,Breakfast,Canned,...,Small,Tier 1,Tier 2,Tier 3,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,Outlet_Identifier,Outlet_Establishment_Year
0,9.300,0.016047,249.8092,3735.1380,True,False,False,False,False,False,...,False,True,False,False,False,True,False,False,6.0,3.0
1,5.920,0.019278,48.2692,443.4228,False,True,False,False,False,False,...,False,False,False,True,False,False,True,False,1.0,5.0
2,17.500,0.016760,141.6180,2097.2700,True,False,False,False,False,False,...,False,True,False,False,False,True,False,False,6.0,3.0
4,8.930,0.000000,53.8614,994.7052,True,False,False,False,False,False,...,False,False,False,True,False,True,False,False,1.0,5.0
5,10.395,0.000000,51.4008,556.6088,False,True,True,False,False,False,...,False,False,False,True,False,False,True,False,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
7835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
7843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
7847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
7848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0

In [55]:
train_date.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8336 entries, 0 to 7848
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                6113 non-null   float64
 1   Item_Visibility            6113 non-null   float64
 2   Item_MRP                   6113 non-null   float64
 3   Item_Outlet_Sales          6113 non-null   float64
 4   Low Fat                    6113 non-null   float64
 5   Regular                    6113 non-null   float64
 6   Baking Goods               6113 non-null   float64
 7   Breads                     6113 non-null   float64
 8   Breakfast                  6113 non-null   float64
 9   Canned                     6113 non-null   float64
 10  Dairy                      6113 non-null   float64
 11  Frozen Foods               6113 non-null   float64
 12  Fruits and Vegetables      6113 non-null   float64
 13  Hard Drinks                6113 non-null   float64
 14  Health and Hygiene         6113 non-null   float64
 15  Household                  6113 non-null   float64
 16  Meat                       6113 non-null   float64
 17  Others                     6113 non-null   float64
 18  Seafood                    6113 non-null   float64
 19  Snack Foods                6113 non-null   float64
 20  Soft Drinks                6113 non-null   float64
 21  Starchy Foods              6113 non-null   float64
 22  High                       6113 non-null   float64
 23  Medium                     6113 non-null   float64
 24  Small                      6113 non-null   float64
 25  Tier 1                     6113 non-null   float64
 26  Tier 2                     6113 non-null   float64
 27  Tier 3                     6113 non-null   float64
 28  Grocery Store              6113 non-null   float64
 29  Supermarket Type1          6113 non-null   float64
 30  Supermarket Type2          6113 non-null   float64
 31  Supermarket Type3          6113 non-null   float64
 32  Outlet_Identifier          6113 non-null   float64
 33  Outlet_Establishment_Year  7854 non-null   float64
dtypes: float64(34)
memory usage: 2.2 MB

In [54]:
train_date.replace({True:1,False:0},inplace=True)

C:\Users\gaura\AppData\Local\Temp\ipykernel_324\4118648312.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train_date.replace({True:1,False:0},inplace=True)

In [61]:
train_date.dropna(inplace=True)

In [62]:
X=train_date.drop('Item_Outlet_Sales',axis=1)

In [63]:
Y=train_date["Item_Outlet_Sales"]

In [85]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
lmodel=LinearRegression()
lmodel.fit(x_train,y_train)

LinearRegression()

In [86]:
prediction=lmodel.predict(x_test)

In [87]:
prediction

array([  637.6782573 ,  2915.67867776,   866.98885746,  1737.81800233,
        1041.05001803,   987.06449993,  4150.23127636,  2565.7837824 ,
        5150.52818753,  2984.68712921,  2379.19812693,  1474.43000074,
        4272.60439062,  3868.71560438,   664.44619047,  1366.25131236,
        1359.11088705,  4355.64296176,  4243.92949379,  4282.24447476,
         555.62435538,  1644.72098558,  2579.47240925,  1560.87331716,
        1771.48051694,  2325.68145431,  3616.25221807,  2327.66357105,
        3226.0173241 ,  3365.80982171,  1708.77040041,  2171.60873629,
        4941.69603551,  1339.70911148,  1472.41540302,  3843.12065559,
        1633.24481089,   597.2572657 ,  2612.16633597,  1633.88304546,
        2397.168861  ,  1766.75511904,  1982.14037278,  3243.19132267,
        1984.65306008,  1576.15615039,  2365.58814705,  4160.87733564,
        1364.21036416,  2493.46705315,  2358.5491379 ,   928.362432  ,
        1389.65933233,  1121.84669772,  1656.81797026,  2777.11256488,
        1923.43457517,   870.85949   ,  1194.58104881,  4100.25130687,
         165.99531971,   718.03608298,  2146.63134251,  3981.16685707,
        4170.69224068,  1316.67971668,  1891.22751891,  1446.77908616,
        4400.55614202,  -249.08258739,   323.69058482,   -53.21134418,
        3109.75865249,  3887.7742339 , -1035.46238766,  2633.07349028,
         620.77117446,   864.98174506,  3814.24946415,  2499.68224736,
        3148.33259836,  1472.61415827,  1614.2871139 ,  4458.61392422,
        3942.07751722,    55.58041257,  2916.72272914,   855.63408892,
        4577.16683227,  1711.51795615,   726.97914523,  1067.09497067,
        5232.22265271, -1252.63556231,  4308.80943695,  1906.54690566,
         641.6042103 ,  1905.43472809,  4344.07066364,  4122.66337402,
        3969.06247831,  3165.03825278,  3965.22052587,   578.47111122,
        1360.29978457,   500.13128566,  2949.0289997 ,  2560.15447907,
        5171.67884166,  3029.85375475,  2572.55668935,  1480.54806722,
        1617.78319571,  2574.46220297,  1341.04332948,  2654.53578912,
        3913.83128115,  3317.10324296,  3048.4188409 ,  1912.39541514,
        2318.36431966,  4159.23781491,  2796.20139056,  2936.21109616,
        -894.29051573,  -143.58633839,  1113.9832374 ,  3861.19416765,
       -1215.41372699,  2449.00031034,  3165.75471306,   928.73193783,
        2749.25687031,  1665.81510249,  2311.09323489,  2780.09863276,
        1028.41064422,  2049.99247198,  3775.03090776,  1459.20187593,
         777.92230373,   636.62882031,  2070.17840903,  3465.46267361,
        3823.69043817,   -96.58639201,  1540.39425763,  2780.98097247,
        1092.1592649 ,  4379.89512573,  1920.65502791,  2086.01345672,
        2080.4018086 ,  3048.94629992,  2765.96261147,  3680.77645548,
        1896.82814202,  2847.99653764,  2980.50958436,  3097.28425829,
        2954.5844772 ,  1832.64555118,   865.35685649,  1130.48901509,
        2613.76493584,  1551.78426441,  3065.28466463,  3725.09304207,
        4225.74012669,  2479.45146477,   860.88508439,  3198.32744468,
        2050.68601471,  3514.53581387,  -186.49609687,  3766.61157296,
         569.04145102,   734.72288445,  3443.89298409,  2525.83906183,
        4028.85848588,  3441.79352173,   605.48066024,  1037.17895433,
         645.92090172,  1939.41962846,  1279.99157801,  3111.21487852,
        2550.79611131,  3829.53406144,  1115.40717807,  1713.57896913,
        2406.79952907,   792.35799618,   706.75424952,  2650.08094532,
        3782.09266336,  3801.82625321,  -973.5183749 ,  3213.0025316 ,
        3600.40863196,  3581.60736317,  5651.01108405,  4592.40323832,
        3867.54030275,  -439.85325567,  1976.55213519,  2577.52108434,
        2937.82630055,  3766.29526906,  4222.04290406,   952.62080652,
        1115.47414623,  2643.95041544,  1442.43433507,  1484.66301074,
        2460.49130764,   757.76137544,  2962.67550521,  1972.94578013,
        3327.33014208,   551.40719523,  1957.70796079,  5413.9252936 ,
        3019.5788099 ,  3516.70920681,  2106.94314726,  2525.61686353,
        3163.92131171,  2000.37047068,  2807.91885309,  2953.30860571,
        4017.9443712 ,  1725.24673645,   835.24159491,   595.34392167,
        3024.02282651,  1295.66579622,   568.37543323,  1759.02659622,
         509.23825527,  1160.62000429,  2937.16624055,  5292.6751302 ,
        2216.84809711,  3472.02429688,  1348.66154322,   893.9445392 ,
        4346.15610413,  3174.30133217,  3259.29930993,  2706.1294841 ,
        3173.93570869,   -76.88953626,  5429.21708147,  2077.81357117,
        3870.59978869,  4243.92520876,   686.92520255,  2379.8049474 ,
         623.82495276,   159.3647881 ,  1607.22916008,  1931.1206662 ,
        2424.54833131,  2117.0459976 ,  1620.04140489,  3906.74472066,
        5686.18668182,   147.50142552,  2056.93268432,  2226.8413717 ,
        2199.34808403,  2070.09952114,  -411.70119381,  2617.75002896,
        3238.98722689,  1119.38037662,  4055.56979682,  5255.60592559,
        3607.97834155,   775.68462033,  3722.83450359,  2414.95882664,
        2045.30463461,  3083.77799055,  1222.71814288,  2319.96082688,
        4843.81330338,  3116.19035207,  -926.48577333,  3100.83786606,
        -839.80187604,  2492.68917297,   754.6613761 ,  3154.01514209,
         678.45243706,  3628.30502619,  2419.83053823,  2337.40573317,
        2887.43998076,  1822.83549077,  2840.5557209 ,  3303.82231447,
        2557.28699048,  2953.89343002,  3645.03448151,  3774.50621327,
        2816.16663989,  1816.6142979 ,  1974.95398829,  1781.39173607,
        4357.79904535,   790.05448649,  1287.98960434,  1094.15747704,
          57.42416438,  1131.55068959,  1626.49502293,   865.95953924,
         761.27246879,  1112.39193282,  1743.09703106,   826.90771268,
        -458.37385194,   961.6712904 ,  1035.4865126 ,  3112.26439331,
        -988.52849396,   442.28092776,  3463.32473756,  1789.44508296,
        2732.11670716,  4537.63691586,  3168.24108328,  4532.10722558,
        2470.41999097,  3686.4339828 ,  3082.22713286,  2034.33705155,
        2772.21179825,  1382.24546048,  2878.02623282,  3598.96482661,
        2687.68492901,  2671.41757329,  2685.31178813,  1472.36686488,
         595.46551079,  2908.48820656,   932.19700381,  5406.07936193,
         873.82540323,   359.90626405,  1898.32297457,  2747.5801466 ,
        1842.87151003,  2170.06713946,  3205.24123807,  2872.73851794,
        -354.30207315,   841.71944773,   194.12913263,   820.90136747,
         857.2198039 ,  2823.68234112,   620.01374639,  3467.58388975,
        2037.02879187,   366.19671543,  3224.62434597,   350.49212906,
        2509.77039599,  4352.44257597,  4251.60876616,  1948.39205222,
        3469.40337982,  2729.85768169,  2044.72013038,  2498.39164914,
         914.6645832 ,  2399.7427721 ,  1733.35908965,  3460.47176229,
        1571.02618021,  3953.429192  ,  3266.1994044 ,  3178.67261088,
         879.66805997,   393.69388378,  3892.30460814,  2539.80718432,
        3145.39553856,  1772.61608558,  4811.17564697,  3014.69457939,
        4502.56514552,  3018.32751102,  3076.75231088,  1591.76465596,
        2149.82385301,   942.23346882,  2610.79258647,  1783.49335643,
        2622.06595144,  1832.64518068,  1092.43450347,  2643.730194  ,
        2494.33739177,  4379.14601541,  3030.5317314 ,  1307.87086415,
        3645.56414583,  2058.52103669,  3995.93797629,  3302.08227121,
        1417.39826845,   255.11328612,  2118.58524045,  4360.21896271,
        2489.1024409 ,  2248.45775846,  4348.22904559,   973.5964953 ,
         865.70469081,  3001.82858283,  2001.79439395,   429.23015836,
        2011.47664073,  -266.80323219,   803.37403022,  3382.62325553,
        3575.30382888,  1852.29625204,  1585.62054364,   708.82883871,
        3969.12306498,  1623.75510595,  4413.13224195,  3743.25736772,
        3032.91428298,  3071.99739699,  3466.47296892,  1991.39490548,
         352.52374388,  3154.4824913 ,  4139.57918822,  2076.05905067,
        3162.07889808,  3821.57563449,  3049.7465241 ,  2342.7746647 ,
        1384.30262906,   469.8978718 ,  3945.25163046,   434.22230287,
         600.88887807,  3896.9291643 ,  3470.91670765,  2295.28626872,
        2086.98493897,  1960.83482411,  2998.08177905,  2918.47047996,
        2569.54635955,  3900.66865559,  3479.05678303,  2396.24950399,
        4658.77313447,  2048.33738761,  4551.49291016,  4388.73904242,
        2980.12110918,  2990.52079085,  2326.64762336,  1911.7191445 ,
        3444.88221714,   531.20385299,  2004.88969925,  2737.42818522,
        3212.66416063,  1310.22400333,  4325.09587146,  1338.32357858,
         143.6157152 ,  2916.7643414 ,  1440.91541219,   454.61768862,
        2433.25235137,  1166.24540712,  2960.33198431,  2604.29383919,
        2696.72759613,  1864.19699505,  4498.18817181,  1527.45399878,
        3984.45176403,  3003.07302184,   833.96946404,  2608.48124595,
        2971.95386458,  1746.36097682,  1521.27253696,  4158.65702551,
        2651.80564143,  2799.36637421,  4152.65001869,   -42.68811261,
        3490.52236832,  1715.57715201,  3003.03518356,  3069.92988144,
        3066.30341434,  3985.9483434 ,   483.73599321,   888.34206684,
        1651.0673395 ,  1042.51757511,  2679.19019256,   920.96789959,
        1206.11281855,  1494.71060827,  2520.65720645,  1372.19120271,
         620.43249257,  1751.60277747,  4534.5803816 ,  1628.92905664,
        3766.9772647 ,  3313.67629643,   677.79397062,  3088.59597571,
        3395.56106447,  1967.72478472,  2045.65417459,  4390.2190083 ,
        5030.72019421,  4347.5110711 ,  4326.87070133,  4155.18409868,
        2738.84129285,  3862.43449254,  2374.97194596,  3175.15045533,
        2797.89662757,   528.40738631, -1398.44305319,  1537.76729054,
        1617.99650474,  2407.56392106,  3238.21225574,  3985.4508373 ,
        4123.48460903,   894.29548615,  1346.75378852,   879.93049676,
        1906.31683106,  3280.23674565,  4647.53675287,  1697.56468632,
        3280.02023629,  2912.17772206,  2653.17009854,   622.24524402,
        2664.19596443,  1508.17097279,  3191.43339994,  2148.95138212,
        3021.60374155,  1524.5243911 ,  3046.8615917 ,  4495.61824385,
        2567.78493022,  2354.37476958,  1556.02758801,   158.39051971,
        3021.11783112,  4236.96787628,  3400.03887913,  1490.15588582,
        2699.63608572,  2632.27859765,  1457.88701312,  5807.38516779,
         733.12510035,  2332.35208941,  1818.22663342,   954.79690067,
        1240.12911681,  3936.75699395,  2711.43135333,  4358.83369834,
        1825.22801114,  3273.54875986,  4449.47445763,  2828.28614506,
        3400.98343538,  1439.81495945,  2782.16372919,  1908.76793777,
        2555.23891888,  2347.92777307,   649.34064685,  3956.33574529,
        1806.34147325,  1261.96876492, -1321.88649154,  1713.43608321,
        2975.37353369,  2079.08806555,  2202.82176365,  1517.18250667,
        2158.70494727,  2548.64453764,  1948.52192976,  1976.98691543,
        2646.46333328,  1286.10036508,  1769.58427284,  3858.73840216,
        2919.26748797,   566.80795486,  3196.15526012,  1024.1058527 ,
        3024.4327077 ,  1304.15591113,  1813.97861857,  1741.041061  ,
        1949.70391252,  2612.74047783,  3700.31207198,  4316.13294189,
        3759.94162854,  1604.72438798,  2623.43675148,  1541.25684631,
        2747.37108882,  -678.85740923,   537.83527331,  3238.63255076,
        4015.69837678,   336.69412925,  3270.43227576,  1813.4089362 ,
        2924.38354006,  1138.43800718,  1192.45705   ,  2950.35267344,
        1805.91531454,   798.02231022,  1445.12837372,  3333.24057398,
        3089.24632047,  3470.59940677,   604.60534149,  4351.067509  ,
        1762.60781012,  3220.34584957,  1369.91544759,  1705.74575161,
        1646.45902113,  2347.80902626,  3329.12472098,  2362.25695219,
        2455.0770845 ,   782.90852181,   325.86123754,  3421.28325201,
        1742.11236747,  1601.83905678,  2979.35761281,  2487.80393222,
         580.33226854,  2271.82190559,   451.96310925,   613.22325842,
        1988.87336818,  1656.22528639,  2760.81085117,  1877.01678011,
        1592.38895844,  3043.11776066,   377.86081939,  4079.84690605,
        2756.57685551,  2882.29151368,  1573.66278142,  2860.45809652,
        2074.2506186 ,   625.02451831,  2309.91051873,  4493.61134629,
        3287.29112159,  -246.11081041,  3748.33541803,  4013.98554432,
        4187.00535934,  1285.69923268,  5422.13275338,  2626.81488434,
        2236.63326888,  2031.68910555,  4181.11143895,  3727.10161288,
        3002.56996224,  3397.68543764,  2900.79227309,  2797.26458938,
        2306.14904965,  1559.81365719,  -480.79637908,  4439.74014719,
        3776.94763002,  2366.73618187,  2775.46556203,  2068.87630402,
        3810.63559756,  2389.88736785,  3011.3911671 ,  3175.53454238,
        1968.54588019,  2854.95298751,  1931.75299864, -1358.95429898,
        2702.5738563 ,  1426.03535327,  1035.25174089,   130.51851479,
        3267.49746395,   411.92799557,  2675.26919276,  1492.70248364,
        2028.79915731,   503.86584821,  3097.49253769,  2602.90558443,
        2672.90162463,  2843.86406095,  2282.09382708,   678.63962091,
        2214.30359492,  1520.00511295,  3336.85460167,  1747.75053817,
        3210.12384366,  2536.44833649,  2943.79841327,   560.59337077,
        2386.26038404,  2888.9148394 ,  2516.35194891,  1805.20527258,
        4286.35067329,  3099.43739919,  3788.71562119,  2269.27579585,
        2458.49041208,  1662.30436963,  1553.76337244,  1659.13109046,
        2339.62480062,  4315.57321653,  2308.33870448,   728.70952643,
        3781.584399  ,  3817.32693387,  4252.48218274,  -334.16111187,
        4215.52027444,  2381.86556182,  2198.90613752,    30.20946191,
        4044.42472593,  3345.25113211,  2829.85507564,  1960.08085495,
        1632.70724878,   -61.60508697,  1838.57774123,   740.59859256,
        2849.30178306,  1758.79064691,  1838.12790403,  -691.17159154,
        -944.06532486,  1790.33715173,  1862.45470509,  3934.04622163,
        2612.98034207,  1998.87019663,    23.45133756,  3083.87584589,
        3964.15211773,   958.94407213,  3132.39136518,  4084.60880626,
        1847.74415306,    57.55777541,   846.07913617,  1750.96864596,
        1409.65328389,  1780.25649276,  4275.81160798,  2322.90668027,
        2043.73097902,  3148.77125345,  2713.59022303,  3137.21080727,
        4163.45395817,  3081.09624149,  2138.24409963,  3572.4182786 ,
        3831.91248356,  3050.57058948,  4403.06492538,   139.05701551,
        1414.70754792,  2268.07163172,  2197.27484382,  2992.77615309,
        2145.66593674,  2440.61231415,  3361.91581586,  5038.37475732,
        3638.99652913,  2534.89506688,  1610.88965957,  3901.2944258 ,
        3044.3267987 ,   778.2381015 , -1288.94512894,  4570.93734406,
        2215.61262034,  1953.11660704,   685.9382437 ,  2557.67147927,
         803.89224124,  2695.37910977,  3796.45781153,   889.83994023,
        2706.9769047 ,  1908.17022151,  4303.22540747,  3767.87379253,
        2981.96915259,   568.11489647,  3040.81805621,   950.19536659,
        1912.50898902,  2935.17373756,  3766.91343113,  1162.88272869,
         405.55584195,   386.0951926 ,  1798.62468145,  2808.11763801,
        3453.85058172,  1778.67840971,  2779.09127429,  2596.04973103,
         948.01385239,  2424.85172088,  1804.85249639,  2256.64966987,
        3154.81761681,  1693.61939216,  3108.3505193 ,  2488.86970932,
         690.41829347,  -524.76408487,  2550.18556407,  4495.41295265,
        2405.4204834 ,  1934.17878865,  2237.71749153])

In [88]:
print(r2_score(y_test,prediction))

0.5022298499401581